// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjJtX7sn_jlxh47PIFND3PvmnTAL0CeK0',
    appId: '1:787846661940:android:a5021bd1b9e2c7a5ad0761',
    messagingSenderId: '787846661940',
    projectId: 'fir-login-a3cfe',
    databaseURL: 'https://fir-login-a3cfe-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a3cfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ59pGgvwa3C2D7u0U6o-CfEIdTqBtgzY',
    appId: '1:787846661940:ios:984b6cc3beeb5222ad0761',
    messagingSenderId: '787846661940',
    projectId: 'fir-login-a3cfe',
    databaseURL: 'https://fir-login-a3cfe-default-rtdb.firebaseio.com',
    storageBucket: 'fir-login-a3cfe.firebasestorage.app',
    androidClientId: '787846661940-f91484l15atnae3ka9cdknc5ojmfqj2h.apps.googleusercontent.com',
    iosClientId: '787846661940-u3n66te97glkf05v120hb9kmelkdm7lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
